
on: push
name: Update workshop branch
jobs:
  updateBranch:
    name: Update workshop branch
    runs-on: ubuntu-latest
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Github Token
        with:
          branch: 'release'
          sha: '${{ github.event.pull_request.head.sha }}'
